- name: Remove old html (important)
  file:
    path: /var/www/html
    state: absent

- name: Recreate html directory
  file:
    path: /var/www/html
    state: directory

- name: Copy server1
  copy:
    src: "{{ playbook_dir }}/server1/"
    dest: /var/www/html/server1/

- name: Copy server2
  copy:
    src: "{{ playbook_dir }}/server2/"
    dest: /var/www/html/server2/