- name: Create server1 directory
  file:
    path: /var/www/html/server1
    state: directory

- name: Create server2 directory
  file:
    path: /var/www/html/server2
    state: directory

- name: Copy server1 files
  copy:
    src: "{{ playbook_dir }}/server1/"
    dest: /var/www/html/server1/

- name: Copy server2 files
  copy:
    src: "{{ playbook_dir }}/server2/"
    dest: /var/www/html/server2/